- name: Install neovim based on OS
  tags: nvim
  block:
    - name: Install on Ubuntu
      ansible.builtin.include_tasks: ubuntu.yml
      when: ansible_distribution == "Ubuntu"

    - name: Install on Fedora
      ansible.builtin.include_tasks: fedora.yml
      when: ansible_distribution == "Fedora"

    - name: Install on Arch Linux
      ansible.builtin.include_tasks: arch.yml
      when: ansible_os_family == "Archlinux"

    - name: Clone repo
      ansible.builtin.git:
        repo: https://codeberg.org/krystek/dotfiles.git
        dest: /tmp/dotfiles
        version: master

    - name: Create config folder
      ansible.builtin.file:
        name: .config
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0754"

    - name: Move nvim config
      ansible.builtin.copy:
        src: "/tmp/dotfiles/nvim"
        dest: "/home/{{ username }}/.config/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0754"
        remote_src: true

    - name: Install npm package
      comumunity.general.npm:
        name: neovim
        global: true

    - name: Install pip module
      ansible.builtin.pip:
        name: pynvim
        executable: pip3
